### ISSUE TITLE
Hybrid first test

### ISSUE THREAD

**Issue by xianbo** [xianbo/ShadowOui-HYBRID#12]
Hi Luca,
On line 1050,
numpy.gradient(wmirror_l.np_array, wmirror_l.delta(), edge_order=2)
This cannot run with numpy version 1.8, the edge_order parameter started in version 1.9.1

For the example hybrid_mirror.ows, It works when I run everything from the source. After I run it once, I run only the hybrid screen itself, then it show wrong results. In another word, if I just disable the connection from the mirror to hybrid screen and enable it, I will get wrong results. I can see each time I do that the star.02 file changes. 

Xianbo

**Comment by lucarebuffi** [comment]
see Pull Request #13

https://github.com/xianbo/ShadowOui-HYBRID/pull/13
